<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-2L7QON7" failures="1" tests="4" name="AppLaunchTests" time="33.964" errors="0" timestamp="2023-12-03T22:04:09 IST">
  <testcase classname="com.testng.demo.TestNgDemo1" name="verifyAppLaunchInEdge1" time="9.66">
    <failure type="java.lang.AssertionError" message="Error message which tells the failure details">
      <![CDATA[java.lang.AssertionError: Error message which tells the failure details
at com.testng.demo.TestNgDemo1.verifyAppLaunchInEdge1(TestNgDemo1.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- verifyAppLaunchInEdge1 -->
  <testcase classname="com.testng.demo.TestNgDemo1" name="verifyAppLaunchInChrome1" time="7.6"/>
  <testcase classname="com.testng.demo.TestNgDemo2" name="verifyAppLaunchInEdge2" time="8.142"/>
  <testcase classname="com.testng.demo.TestNgDemo2" name="verifyAppLaunchInChrome2" time="8.453"/>
</testsuite> <!-- AppLaunchTests -->
